[project]
name = "dpm"
version = "0.0.0.9001"
description = "A package for install, update and manage sources of sets of datapackages"
readme = "README.md"
dependencies = [
  'frictionless',
  'requests'
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"