name: CI tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        py-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.py-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
      - run: python -m pip install .[dev]
      - run: make coverage
      - name: Use Codecov to track coverage
        if: matrix.os == 'ubuntu-latest' && matrix.py-versio == '3.12'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
